
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gcdkzwzqxspazmfhippq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjZGt6d3pxeHNwYXptZmhpcHBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4NDM3MTAsImV4cCI6MjA4ODQxOTcxMH0.NDFZVf-Qz5Ca4W_-XDs4aCq5OZc8O7nx0Ryv5Nr0D18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
